"""empty message

Revision ID: 5e1bfd66bfdd
Revises: 3f526812cf39
Create Date: 2023-01-30 17:14:11.256755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1bfd66bfdd'
down_revision = '3f526812cf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
